# Generated by Django 6.0.3 on 2026-03-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię dziecka')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='Grupa krwi')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data bilansu')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Waga (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wzrost (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi lekarskie')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='medical_record.child', verbose_name='Dziecko')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='Nazwa szczepionki')),
                ('date', models.DateField(verbose_name='Data szczepienia')),
                ('status', models.BooleanField(default=False, verbose_name='Czy wykonano?')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='medical_record.child', verbose_name='Dziecko')),
            ],
        ),
    ]
