# Generated by Django 6.0.4 on 2026-04-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.IntegerField(verbose_name='Wiek w miesiącach')),
                ('due_date', models.DateField(verbose_name='Planowana data')),
                ('is_done', models.BooleanField(default=False, verbose_name='Czy wykonano?')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='medical_record.child')),
                ('health_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='medical_record.healthcheck')),
            ],
        ),
    ]
