# Generated by Django 6.0.4 on 2026-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0002_healthcheckschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='abdomen',
            field=models.CharField(blank=True, max_length=200, verbose_name='Brzuch'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ciśnienie tętnicze'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wskaźnik BMI'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='consultations',
            field=models.TextField(blank=True, verbose_name='Zlecone konsultacje'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='diagnostic_tests',
            field=models.TextField(blank=True, verbose_name='Zlecone badania diagnostyczne'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='diet',
            field=models.TextField(blank=True, verbose_name='Dieta/Witaminy'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='ears',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uszy'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='eyes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Oczy'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='Głowa'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='head_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Obwód głowy (cm)'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='health_problems',
            field=models.TextField(blank=True, verbose_name='Problemy zdrowotne'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='hearing',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zaburzenia słuchu'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='heart',
            field=models.CharField(blank=True, max_length=200, verbose_name='Serce'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='lungs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Płuca'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='lymph_nodes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Węzły chłonne'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='mouth',
            field=models.CharField(blank=True, max_length=200, verbose_name='Jama ustna/gardło'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='musculoskeletal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Układ kostno-stawowy'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='neck',
            field=models.CharField(blank=True, max_length=200, verbose_name='Szyja'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='nutrition_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stan odżywienia'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Zalecenia'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='skin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Skóra'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='urogenital',
            field=models.CharField(blank=True, max_length=200, verbose_name='Układ moczowo-płciowy'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='vision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zaburzenia wzroku'),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Masa ciała (kg)'),
        ),
    ]
