# Generated by Django 6.0.4 on 2026-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0004_child_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='PESEL'),
        ),
    ]
