# Generated by Django 6.0.4 on 2026-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0005_child_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Chłopiec'), ('F', 'Dziewczynka')], max_length=1, verbose_name='Płeć'),
        ),
    ]
